### ISSUE TITLE
Lazy load of Pages when routed to?

### ISSUE THREAD

**Issue by jogibear9988** [PolymerLabs/more-routing#51]
Is it possible to Lazy load a File when a Link to a Route is clicked? Like in https://github.com/erikringsmuth/app-router#app-route-options

**Comment by vguillou** [comment]
I don't think you can out of the box.

Is this what you are looking for ?
https://github.com/Plastikit/plastik-lazy-route-selector

**Comment by devAtPolydeals** [comment]
:+1: 

This would be great!
