### ISSUE TITLE
Does this work with Polymer 1.0?

### ISSUE THREAD

**Issue by jogibear9988** [PolymerLabs/more-routing#57]
I try this with Polymer 1.0 but I could not get it to work!

**Comment by Barbayar** [comment]
yeah, seems it doesn't work with Polymer 1.0.
I get 2 errors, when I try to use.
```
"can only manage children that are selectors"
"was built without a selector to manage. It will do nothing."
```

**Comment by Barbayar** [comment]
`app-router` doesn't work as well :(

**Comment by vguillou** [comment]
If you want some help, you should be more specific/show your code.

Here is a working example (even though it highlights issues #52 and #53) :
https://vguillou.github.io/webcomponents/neon-page-behavior/demo/more-routing/index.html

**Comment by dman777** [comment]
Using Polymer 1.1..... I'm new to `more-routing` and trying to get my page to load but I am getting:

 
```
    more-route-selector.html:176 more-route-selector "can only manage children that are selectors"
    more-route-selector.html:114 more-route-selector "was built without a selector to manage. It will do nothing."
```

As far as I can tell, everything looks correct with the example `Or, TL;DR`:




  
```html
      <more-route-selector>
          <iron-pages>
            <section route="home">
              <div class="vertical layout center" style="height: 1000px;">
                <div id="section1">
                  <div clas="horizontal start-justified layout">
                    <h2 class="section-title">Portfolio</h2>
                    <p class="section-description">blah blah,<br> blah blah</p>
                  </div>
                  <div class="layout horizontal center-center">
                    <iron-icon class="big" icon="car"></iron-icon>
                  </div>
              </div>
            </section>
    
            <section route="portfolio">
              <h1>HI</h1>
            </section>
    
            <div id="section2">
              <h1>OTHER</h2>
            </div>
          </iron-pages>
        </more-route-selector>
```
---------------------------------------------------------

```html
    <more-routing-config driver="path"></more-routing-config>
    <more-route name="home" path="/"></more-route>
    <more-route name="portfolio" path="/portfolio"></more-route>
```

**Comment by ethancalvo** [comment]
hey dman777, it looks like you didn't close &lt;div id="section1"&gt;

**Comment by dman777** [comment]
Sorry, I closed it but still had the errors afterwards.

**Comment by PiusLT** [comment]
@dman777 I was having this problem until I realised `iron-pages` wasn't included. I needed this:

    <link rel="import" href="../bower_components/iron-pages/iron-pages.html" />

I am using Polymer version `1.1.1`. Haven't tested more-routing extensively (it's a fresh project) but it seems to work so far.

**Comment by s-devaney** [comment]
Those saying this "works" with Polymer 1.0 must have a very loose definition of "works". urlFor is broken in 1.0, all the demos and documentation is written for 0.5 and there are bugs when using 1.0 elements like neon-animation-pages. I suggest looking elsewhere.

**Comment by PiusLT** [comment]
I didn't test it extensively because I only used it in some small app but yeah, `urlFor` wasn't accessible as in Polymer 0.5. Here is how you use it in Polymer 1.0:

```html
<dom-module id="app-sidebar">
	<template>
		<!-- ... -->
			<a href="{{ urlFor('page-xyz') }}"><!-- ... --></a>
		<!-- ... -->
    </template>

    <script>
    	Polymer({
    		is: "app-sidebar",
    		
    		urlFor: function(pathOrName, params) {
    			return MoreRouting.urlFor(pathOrName, params)
    		}
    	})
    </script>
</dom-module>
```

I wouldn't call it _broken_. I would say it's more like _it changed its name_.

**Comment by s-devaney** [comment]
Have got this working quite nicely with Polymer 1.0 (obviously without urlFor)
